SRC = \
	LargeSizeChar.swift \
	LargeSizeCharFactory.swift \
	LargeSizeString.swift \
	main.swift

PROG = Flyweight

.PHONY: all
all: $(SRC)
	swiftc -o $(PROG) $(SRC)

.PHONY: clean
clean:
	rm -rf $(PROG)
