SRC = \
	BarChartObserver.swift \
	DigitObserver.swift \
	Number.swift \
	Observer.swift \
	RandomNumber.swift \
	main.swift

PROG = Observer

.PHONY: all
all: $(SRC)
	swiftc -o $(PROG) $(SRC)

.PHONY: clean
clean:
	rm -rf $(PROG)
