SRC = \
	AbstractDisplay.swift \
	CharDisplay.swift \
	StringDisplay.swift \
	main.swift

PROG = TemplateMethod

.PHONY: all
all: $(SRC)
	swiftc -o $(PROG) $(SRC)

.PHONY: clean
clean:
	rm -rf $(PROG)
